### ISSUE TITLE
New "Local data management" screen

### ISSUE THREAD

**Issue by MattF-NSIDC** [faunalia/qgreenland-plugin#11]
This ticket is probably really multiple features bundled up in to one. Maybe it should be a "Project" instead of an issue? I've not played with that feature on GitHub before.

On screen 4 of our mockups:

![image](https://user-images.githubusercontent.com/18539827/142905737-99007aef-24a5-4b06-8c38-40fb89c53f25.png)

This screen allows exploring of QGreenland data that exists on the user's computer. Features:

* "Explore data" button shows a warning: "Continue at your own risk. If you move or delete any files from this directory, they will disappear from the QGreenland plugin. Copying is OK."
* Show an icon when updates are available
* Add checked layers to current project.
* If the "include folder structure" checkbox is checked, the layers will be added with group structure.

**Comment by MattF-NSIDC** [comment]
>a user downloads the data in a chosen folder (and we can easily track which one) but after a while (s)he decides to move the data elsewhere and the plugin loose the original reference

We discussed this and we decided that if the user wants to open the plugin storage folder and mess around (move or delete things), they will have to deal with the consequences. The plugin should be capable of re-downloading the moved/deleted layers in that case.

> Show an icon when updates are available
>> isn't this already done in the main downloading window?

Yes, but in our mock-ups we visualized this icon would be shown in both screens.

>make sense, download to a folder and load in the QGIS project.

Just to clarify, we envisioned the "download" and "load in the QGIS project" features be available on separate screens; 1 screen for downloading the data, and another screen for data management (inserting the data into a project, deleting data, etc as described in mockup). For a given layer, the user would only use the download screen once, but would use the "data management" screen _N_ times, as many times as the user needs to add that data to a project.

**Comment by ghtmtt** [comment]
> We discussed this and we decided that if the user wants to open the plugin storage folder and mess around (move or delete things), they will have to deal with the consequences. The plugin should be capable of re-downloading the moved/deleted layers in that case.

I think that the user will save the data somewhere around on the computer, maybe also an usb stick :) as said we can make the plugin track the original path of the folder but every change made by the user to those files/folder cannot be tracked by the plugin anymore. This involves many controls by the plugin itself but we will still not able to have a complete control of it

**Comment by MattF-NSIDC** [comment]
@ghtmtt We've thought a little bit more about what this screen should look like and do. You have a good point about users moving data. We still hold the position that once a user moves data from the plugin storage location, they're on their own. If they delete or move anything, as far as the plugin is concerned, that data is gone.

To address this concern, we think it's best to reduce the scope of the "local data management" screen to include only adding downloaded layers to the project. A "explore files" button will allow the user to view the data files using their operating system's file browser / Finder.

![image](https://user-images.githubusercontent.com/18539827/142905737-99007aef-24a5-4b06-8c38-40fb89c53f25.png)

When the user clicks "Explore files", they will be presented with a warning: "Continue at your own risk. If you move or delete any files from this directory, they will disappear from the QGreenland plugin. Copying is OK."

**Comment by MattF-NSIDC** [comment]
Updated the top-level post to remove the "delete data" requirement and add the warning about moving or deleting data.

**Comment by ghtmtt** [comment]
so the expected behavior is that, when the download is finished, this "Local data management" tab is available with the behavior listed?

**Comment by MattF-NSIDC** [comment]
We're thinking this view should be available independently of the download view, so there would be three completely separate user interfaces: Download, Manage, and Config. We think they should all be available under a QGreenland dropdown menu under the Plugins menu. So to open the different screens you would go to "Plugins > QGreenland > Download" or "Plugins > QGreenland > Manage" to access these screens. If you view the "Manage" screen before downloading anything, it could display a message prompting users to "Please download data first."
