### ISSUE TITLE
Can we notify users in QGIS when a new plugin version is available?

### ISSUE THREAD

**Issue by MattF-NSIDC** [faunalia/qgreenland-plugin#36]
Does QGIS support this in any way?  We'd like beta users to get a notification when a full version is available if possible.

**Comment by ghtmtt** [comment]
yes QGIS has an automatic way to notify the user if there is anew version of a plugin. In the `Plugins -> Manage and install Plugins` menu within the `Settings` tab the user can choose how often QGIS should check for new plugin versions. If any, a new tab `Upgreadable` appears:

![image](https://user-images.githubusercontent.com/2884884/146229363-5b07b19e-7b29-409e-a181-836b6f634505.png)


Moreover, in the bottom right corner of QGIS, if any new version is there, a *puzzle* like icon appears and when clicked it opens the tab of the plugins:

![image](https://user-images.githubusercontent.com/2884884/146229615-43eccabf-8735-40c6-abbc-5b08c567116b.png)

**Comment by MattF-NSIDC** [comment]
Awesome, thanks! We had seen the puzzle icon before but weren't sure how to configure it.
